name: pistachio-simulation
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10 # Explicitly specifying Python version for better compatibility
  - requests
  - xgboost=2.0.3
  - numpy>=1.20
  - pandas=2.1.1
  - matplotlib=3.8.0
  - python-dotenv=1.0.0
  - pydantic=2.10.3
  # - scikit-learn=1.3.2
  - seaborn=0.13.0
  # - optuna=3.5.0
  # - scipy=1.11.3
  - openpyxl=3.1.2
  # Windows-specific dependencies
  - pywin32
  - setuptools
  - pip
